### ISSUE TITLE
启动应用程序出错

### ISSUE THREAD

**Issue by bytrix** [CaledoniaProject/XLCloudClient#23]
怎么打不开呢？提示“启动应用程序出错。”
系统环境：Deepin Linux
![20160718151340](https://cloud.githubusercontent.com/assets/7734124/16907956/3e8395d0-4cb7-11e6-9dd7-8ec44934d905.png)

**Comment by CaledoniaProject** [comment]
不好意思 这个客户端暂停维护了。。

**Comment by CaledoniaProject** [comment]
迅雷的登陆协议发生变化了，我自己也不用Linux了，所以就没在研究
