### ISSUE TITLE
capcha太小了，看不太清楚

### ISSUE THREAD

**Issue by liu-xiao-guo** [CaledoniaProject/XLCloudClient#24]
Capcha图片太小，看不太清楚。有办法做大一点吗？另外关于使用该软件时，我现在使用verycd网页，是不是直接在网页中搜到相应视频的链接地址，然后打开New Task就可以了？在我这里下载不了。

[INFO] Getting capcha code ..
[NOTICE] Capcha required, retrieving ..
[NOTICE] Capcha received, size 2168
[INFO] Login .. cookie: ENYN
[WARNING] Cannot retrieve jumpkey, is the protocol changed?
[WARNING] Protocol changed or parser failure (incorrect column count), submit this line: document.cookie ="sessionid=; path=/; domain=xunlei.com"; document.cookie ="lx_sessionid=; path=/; domain=vip.xunlei.com";top.location='http://lixian.vip.xunlei.com/task.html?error=1'
[NOTICE] Task added, reloading page ..
[INFO] Parsing task data ..
[WARNING] JSON parse error! Was the protocol changed?

**Comment by CaledoniaProject** [comment]
不好意思，这个项目停止维护了。。
